name: Version check

on:
  pull_request:


jobs:
  # version-check:
  #   uses: kokoichi206/actions-diff-and-notify/.github/workflows/version-check.yml@732fbec20ec7e9322a04c68cc5f77126177edc44
  create-release:
    uses: kokoichi206/actions-diff-and-notify/.github/workflows/create-release.yml@release
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
